name: CVE Scanning

on:
  workflow_dispatch:
  push:
    branches:
    - main
#   workflow_call:
#     inputs:
#       flavor:
#         required: true
#         type: string
#       flavor_release:
#         required: true
#         type: string
#       family:
#         required: true
#         type: string
#       release_matcher:
#         required: false
#         type: string

concurrency:
    group: ci-scan-${{ github.head_ref || github.ref }}-${{ github.repository }}
    cancel-in-progress: true



jobs:
  get-matrix:
    runs-on: fast
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --prune --unshallow
          sudo apt update && sudo apt install -y jq
      - id: set-matrix
        run: |
          # content=`cat .github/flavors.json  | jq 'map(select(.variant == "core" and .arch == "amd64"))'`
          content=`cat images.json`
          # the following lines are only required for multi line json
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          # end of optional handling for multi line json
          echo "::set-output name=matrix::{\"include\": $content }"
  cve-scan:
    needs:
      - get-matrix
    strategy:
        fail-fast: false
        matrix: ${{fromJson(needs.get-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    name: ${{ matrix.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
    - name: Install earthly
      uses: Luet-lab/luet-install-action@v1.1
      with:
        repository: quay.io/kairos/packages
        packages: utils/earthly
    - name: Run CVE scans
      run: |
        earthly +security-scan --CONTAINER_IMAGE=${{ matrix.image }} --LEVEL=critical
    - name: collect results
      if: failure()
      run: |
        earthly +security-report --CONTAINER_IMAGE=${{ matrix.image }}
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ matrix.tag_name }}-reports.logs.zip
        path: build/**/
        if-no-files-found: warn

    # - name: save commit-message
    #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} && failure()
    #   run: echo "COMMIT_MSG=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV
    - name: notify if scanning fails
      if: failure()
      uses: slackapi/slack-github-action@v2.0.0
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
            {
                "blocks": [
                {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "Security check failed ${{ github.job }} in workflow \"${{ github.workflow }}\"\nImage: ${{ matrix.image }}"
                    }
                },
                {
                    "type": "divider"
                },
                {
                    "type": "actions",
                    "elements": [
                    {
                        "type": "button",
                        "text": {
                        "type": "plain_text",
                        "text": "Security reports",
                        "emoji": true
                        },
                        "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                        "type": "button",
                        "text": {
                        "type": "plain_text",
                        "text": "Repository link",
                        "emoji": true
                        },
                        "url": "https://github.com/${{ github.repository }}"
                    }
                    ]
                }
                ]
            }
